// Code generated by counterfeiter. DO NOT EDIT.
package v6fakes

import (
	sync "sync"

	v6 "code.cloudfoundry.org/cli/command/v6"
)

type FakeCurlActor struct {
	MakeRequestStub        func(string) (string, string, string)
	makeRequestMutex       sync.RWMutex
	makeRequestArgsForCall []struct {
		arg1 string
	}
	makeRequestReturns struct {
		result1 string
		result2 string
		result3 string
	}
	makeRequestReturnsOnCall map[int]struct {
		result1 string
		result2 string
		result3 string
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeCurlActor) MakeRequest(arg1 string) (string, string, string) {
	fake.makeRequestMutex.Lock()
	ret, specificReturn := fake.makeRequestReturnsOnCall[len(fake.makeRequestArgsForCall)]
	fake.makeRequestArgsForCall = append(fake.makeRequestArgsForCall, struct {
		arg1 string
	}{arg1})
	fake.recordInvocation("MakeRequest", []interface{}{arg1})
	fake.makeRequestMutex.Unlock()
	if fake.MakeRequestStub != nil {
		return fake.MakeRequestStub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3
	}
	fakeReturns := fake.makeRequestReturns
	return fakeReturns.result1, fakeReturns.result2, fakeReturns.result3
}

func (fake *FakeCurlActor) MakeRequestCallCount() int {
	fake.makeRequestMutex.RLock()
	defer fake.makeRequestMutex.RUnlock()
	return len(fake.makeRequestArgsForCall)
}

func (fake *FakeCurlActor) MakeRequestCalls(stub func(string) (string, string, string)) {
	fake.makeRequestMutex.Lock()
	defer fake.makeRequestMutex.Unlock()
	fake.MakeRequestStub = stub
}

func (fake *FakeCurlActor) MakeRequestArgsForCall(i int) string {
	fake.makeRequestMutex.RLock()
	defer fake.makeRequestMutex.RUnlock()
	argsForCall := fake.makeRequestArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeCurlActor) MakeRequestReturns(result1 string, result2 string, result3 string) {
	fake.makeRequestMutex.Lock()
	defer fake.makeRequestMutex.Unlock()
	fake.MakeRequestStub = nil
	fake.makeRequestReturns = struct {
		result1 string
		result2 string
		result3 string
	}{result1, result2, result3}
}

func (fake *FakeCurlActor) MakeRequestReturnsOnCall(i int, result1 string, result2 string, result3 string) {
	fake.makeRequestMutex.Lock()
	defer fake.makeRequestMutex.Unlock()
	fake.MakeRequestStub = nil
	if fake.makeRequestReturnsOnCall == nil {
		fake.makeRequestReturnsOnCall = make(map[int]struct {
			result1 string
			result2 string
			result3 string
		})
	}
	fake.makeRequestReturnsOnCall[i] = struct {
		result1 string
		result2 string
		result3 string
	}{result1, result2, result3}
}

func (fake *FakeCurlActor) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.makeRequestMutex.RLock()
	defer fake.makeRequestMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeCurlActor) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ v6.CurlActor = new(FakeCurlActor)
